version: '3'
services:
  backend:
    build:
      context: ./BACK
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - frontend

  frontend:
    build:
      context: ./FRONT
      dockerfile: Dockerfile
    ports:
      - 3000:3000